# Generated by Django 4.2.10 on 2024-03-13 10:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20240225_0800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="از نام اصلی خود استفاده کنید.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="از نام خانوادگی اصلی خود استفاده کنید.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("TEACHER", "Teacher"), ("STUDENT", "Student")],
                default="STUDENT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="کاراکترهای مجاز: حروف انگلیسی، اعداد و @/./+/-/_",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
